rewrote the subset selector for sgrid, added test based on example notebook
asascience-open/xarray-subset-grid pull request #61
Opened 2024-09-09 20:34 UTC by jay-hennen

2024-09-09 21:03 UTC, ChrisBarker-NOAA requested changes
we need to clean up the tests and examples before merging.

And there should be a notebook example -- is there one already? hopefully with some graphics. See: xarray_subset_grid/visualization/mpl_plotting.py

We should add somenthing there for SGRIDS.




See:

2024-09-09 21:33 UTC, jay-hennen commented on tests/test_grids/test_sgrid.py
> +    fs = fsspec.filesystem(
I added the arakawa_c_test_grid from gridded for future tests. Will add another offline test soon

2024-09-09 21:38 UTC, ChrisBarker-NOAA commented on tests/test_grids/test_sgrid.py
> +    fs = fsspec.filesystem(
thanks!

2024-09-10 18:07 UTC, ChrisBarker-NOAA commented on tests/utilities.py
> +from .get_remote_data import get_datafile
we don't want to put this in xarray_subset_grid.

I imagine we will put something like this in libgoods, or maybe gridded, but not here.

2024-09-10 18:07 UTC, ChrisBarker-NOAA commented on tests/utilities.py
> +def get_test_file_dir():
we can just put this in the test file directly -- or *maybe* make it a fixture.

And pathlib is great:

from pathlib import Path

`test_file_dir = Path(__file__).parent /  `'test_data')`

2024-09-10 18:07 UTC, ChrisBarker-NOAA commented on tests/test_grids/test_sgrid.py
> +    breakpoint()
we don't want this in there :-)

2024-09-10 18:07 UTC, ChrisBarker-NOAA commented on tests/test_grids/test_sgrid.py
> +
I tend to put this inline:

`TEST_DIR = Path(__file__).parent.parent / 'test_data'`

`sample_sgrid_file = TEST_DIR / 'arakawa_c_test_grid.nc'`

2024-09-10 18:09 UTC, ChrisBarker-NOAA commented
are the tests running / passing in your repo? 

Check the "actions" tab in the project page.

If not -- I wonder why not?

2024-09-13 20:48 UTC, ChrisBarker-NOAA commented
Looks good--- thanks!

I'd love to see more examples and tests, and plotting, but for now this is an improvement.

2024-09-13 20:48 UTC, merged